### ISSUE TITLE
Improve demo JS quality

### ISSUE THREAD

**Issue by yschimke** [rsocket/rsocket-demo#1]
ideas - allow setting query, initial request n, submit. Use a reactive data sink for databinding.

cc @josephsavona low priority, but I'm betting my shitty DOM code and search for "peace" will annoy you enough to show me how it's meant to be done :)

**Comment by josephsavona** [comment]
I took a look at the code, honestly it seems fine. If we added a reactive sink we'd just have Flowable -> Observable -> DOM instead of Flowable -> DOM. Eh?

**Comment by yschimke** [comment]
fine by me.  I might use this as an excuse to dabble with React e.g. https://facebook.github.io/fixed-data-table/example-object-data.html
